# http://www.zimmers.net/anonftp/pub/cbm/programming/cbm-basic-tokens.txt
from commodore import c2_0

keywords = c2_0.keywords + [
    ("rgr", 0xcc),
    ("rclr", 0xcd),
    ("rlum", 0xce),
    ("joy", 0xcf),
    ("rdot", 0xd0),
    ("dec", 0xd1),
    ("hex$", 0xd2),
    ("err$", 0xd3),
    ("instr", 0xd4),
    ("else", 0xd5),
    ("resume", 0xd6),
    ("trap", 0xd7),
    ("tron", 0xd8),
    ("troff", 0xd9),
    ("sound", 0xda),
    ("vol", 0xdb),
    ("auto", 0xdc),
    ("pudef", 0xdd),
    ("graphic", 0xde),
    ("paint", 0xdf),
    ("char", 0xe0),
    ("box", 0xe1),
    ("circle", 0xe2),
    ("gshape", 0xe3),
    ("sshape", 0xe4),
    ("draw", 0xe5),
    ("locate", 0xe6),
    ("color", 0xe7),
    ("scnclr", 0xe8),
    ("scale", 0xe9),
    ("help", 0xea),
    ("do", 0xeb),
    ("loop", 0xec),
    ("exit", 0xed),
    ("directory", 0xee),
    ("dsave", 0xef),
    ("dload", 0xf0),
    ("header", 0xf1),
    ("scratch", 0xf2),
    ("collect", 0xf3),
    ("copy", 0xf4),
    ("rename", 0xf5),
    ("backup", 0xf6),
    ("delete", 0xf7),
    ("renumber", 0xf8),
    ("key", 0xf9),
    ("monitor", 0xfa),
    ("using", 0xfb),
    ("until", 0xfc),
    ("while", 0xfd),
]

