# http://www.zimmers.net/anonftp/pub/cbm/programming/cbm-basic-tokens.txt
from commodore import c2_0

keywords = c2_0.keywords + [
    ("GRAPHIC", 0xCC),
    ("OLD", 0xCD),
    ("TURN", 0xCE),
    ("PEN", 0xCF),
    ("DRAW", 0xD0),
    ("MOVE", 0xD1),
    ("POINT", 0xD2),
    ("KILL", 0xD3),
    ("WRITE", 0xD4),
    ("REPEAT", 0xD5),
    ("SCREEN", 0xD6),
    ("DOKE", 0xD7),
    ("RELOC", 0xD8),
    ("FILL", 0xD9),
    ("RTIME", 0xDA),
    ("BASE", 0xDB),
    ("PAUSE", 0xDC),
    ("POP", 0xDD),
    ("COLOR", 0xDE),
    ("MERGE", 0xDF),
    ("CHAR", 0xE0),
    ("TAKE", 0xE1),
    ("SOUND", 0xE2),
    ("VOL", 0xE3),
    ("PUT", 0xE4),
    ("PLACE", 0xE5),
    ("CLS", 0xE6),
    ("ACCEPT", 0xE7),
    ("RESET", 0xE8),
    ("GRAB", 0xE9),
    ("RDOT", 0xEA),
    ("PLR$", 0xEB),
    ("DEEK", 0xEC),
    ("JOY", 0xED)
]
