disque_keywords = [
    ("FORME", 0xFFA7),  # as
    ("CHAMPS", 0xD0),  # field
    ("CHANGENOM", 0xD6),  # rename
    ("CHARGE", 0xD3),  # load
    ("CHARGEM", 0xd34d),  # loadm
    ("COPIER", 0xDE),  # copy
    ("CVN", 0xFFA2),  # cvn
    ("DETRUIS", 0xD2),  # kill
    ("DOS", 0xE1),  # dos
    ("DSQI$", 0xDF),  # dski$
    ("DSQO$", 0xE0),  # dsko$
    ("DSQSTR", 0xDC),  # dskini
    ("ECRIT", 0xD9),  # write
    ("FERME", 0xDB),  # unload
    ("FUSIONNE", 0xD5),  # merge
    ("JUSTD", 0xD7),  # rset
    ("JUSTG", 0xD4),  # lset
    ("LIBRE", 0xFFA3),  # free
    ("LOC", 0xFFA4),  # loc
    ("LOF", 0xFFA5),  # lof
    ("MKN$", 0xFFA6),  # mkn$
    ("REP", 0xCE),  # dir
    ("REPODUIT", 0xDD),  # backup
    ("COPIE", 0xD8),  # save
    ("COPIEM", 0xd84d),  # savem
    ("TAMPONS", 0xD1),  # files
    ("UNITE", 0xCF),  # drive
    ("VERIFICATION", 0xDA),  # verify
]
