ext_keywords = [
    ("ADRESSE", 0xFF9D),  # varptr
    ("ATN", 0xFF94),  # atn
    ("CERCLE", 0xC2),  # circle
    ("CHAINE$", 0xFFA1),  # string$
    ("COS", 0xFF95),  # cos
    ("COULEUR", 0xC1),  # color
    ("DCHARGE", 0xCA),  # dload
    ("DCHARGEM", 0xca4d),  # dloadm
    ("DEF", 0xB9),  # def
    ("DEL", 0xB5),  # del
    ("ECRAN", 0xBF),  # screen
    ("MODIFIER", 0xB6),  # edit
    ("EXP", 0xFF97),  # exp
    ("FAIS", 0xBA),  # let
    ("FIX", 0xFF98),  # fix
    ("FN", 0xCC),  # fn
    ("HEX$", 0xFF9C),  # hex$
    ("INTXT", 0xFF9E),  # instr
    ("LIGNE", 0xBB),  # line
    ("LOG", 0xFF99),  # log
    ("PIENDRE", 0xC3),  # paint
    ("PDEFINIR", 0xBD),  # pset
    ("PCOPIE", 0xC7),  # pcopy
    ("PEFF", 0xBC),  # pcls
    ("JOUER", 0xC9),  # play
    ("PMODE", 0xC8),  # pmode
    ("PREINIT", 0xBE),  # preset
    ("POS", 0xFF9A),  # pos
    ("PPOINT", 0xFFA0),  # ppoint
    ("PRAZ", 0xC0),  # pclear
    ("PRENDS", 0xC4),  # get
    ("RAC", 0xFF9B),  # sqr
    ("RANGE", 0xC5),  # put
    ("RENUM", 0xCB),  # renum
    ("SUIVANT", 0xCD),  # using
    ("TAN", 0xFF96),  # tan
    ("TE", 0xFF9F),  # timer
    ("TRACE", 0xC6),  # draw
    ("TROFF", 0xB8),  # troff
    ("TRON", 0xB7),  # tron
]
