super_keywords = [
    ("ATTR", 0xF8),  # attr
    ("BOUTON", 0xFFA9),  # button
    ("CASS", 0xF0),  # brk
    ("CMP", 0xF6),  # cmp
    ("ERR", 0xEF),  # err
    ("HCERCLE", 0xE9),  # hcircle
    ("HCOULEUR", 0xE7),  # hcolor
    ("HDEFINIR", 0xF3),  # hset
    ("HECRAN", 0xE4),  # hscreen
    ("HECRIS", 0xEE),  # hprint
    ("HEFF", 0xE6),  # hcls
    ("HLIGNE", 0xEA),  # hline
    ("HPIENDRE", 0xE8),  # hpaint
    ("HPOINT", 0xFFAA),  # hpoint
    ("HPREINIT", 0xF4),  # hreset
    ("HPRENDS", 0xEB),  # hget
    ("HRANGE", 0xEC),  # hput
    ("HSTAT", 0xF2),  # hstat
    ("HTAMP", 0xED),  # hbuff
    ("HTRACE", 0xF5),  # hdraw
    ("LARGEUR", 0xE2),  # width
    ("LGARNIS", 0xE5),  # lpoke
    ("LIMAGE", 0xFFA8),  # lpeek
    ("LINER", 0xFFAC),  # hlin
    ("LOCALISER", 0xF1),  # locate
    ("NUMER", 0xFFAB),  # erno
    ("PALETTE", 0xE3),  # palette
    ("RGB", 0xF7),  # rgb
]
